"use server";
import { GoogleGenerativeAI } from "@google/generative-ai";
import { prisma } from "@/lib/db";
import { ocr } from "@/generated/prisma";
import { headers } from "next/headers";
const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY!);
export async function deleteMultipleOCR(ids: number[]) {
  if (!Array.isArray(ids) || ids.length === 0) return;

  await prisma.ocr.deleteMany({
    where: {
      id: {
        in: ids,
      },
    },
  });
}
const PROMPT = `
Image Data Extraction Prompt

You are given three images.

Props to extract:
- weight (Int)
- vehicle_number (String)
- address (String)
- map_url (Google Maps URL)
- latitude (float)
- longitude (float)
- date (DateTime)

Example JSON output:

{
  "weight": 1500,
  "vehicle_number": "RJ-20GC-4556",
  "address": "1234 Main St, Cityville, Country",
  "map_url": "https://maps.google.com/?q=12.345678,-98.765432",
  "latitude": 12.34567,
  "longitude": -98.76543,
  "date": "2025-04-25T15:30:00Z"
}

Return only JSON.
`;
const model = genAI.getGenerativeModel({ model: "gemini-2.0-flash" });
export type ExtractDataJsonType = {
  weight: number;
  vehicle_number: string;
  address: string;
  map_url: string;
  latitude: number;
  longitude: number;
  date: Date;
};
export const getFilePart = async (file: File) => {
  const headerList = await headers();
  await prisma.audit.create({
    data: {
      ip: headerList.get("x-forwarded-for") ?? "0.0.0.0",
      message: "File upload",
    },
  });

  return {
    inlineData: {
      mimeType: file.type,
      data: Buffer.from(await file.arrayBuffer()).toString("base64"),
    },
  };
};
export const extractData = async (
  filePart: any,
  maxRetries = 3
): Promise<ExtractDataJsonType> => {
  let attempt = 0;
  while (attempt < maxRetries) {
    try {
      const result = await model.generateContent({
        contents: [
          {
            role: "user",
            parts: [{ text: PROMPT }, filePart],
          },
        ],
      });

      const jsonText = await result.response.text();
      const jsonString = jsonText.replace(/^```json\s*|\s*```$/g, "");
      console.log(`Extracted JSON (attempt ${attempt + 1}):`, jsonString);

      return JSON.parse(jsonString);
    } catch (error) {
      console.error(`Attempt ${attempt + 1} failed:`, error);
      attempt++;

      // Optional: wait before retrying
      await new Promise((res) => setTimeout(res, 500 * attempt));
    }
  }
  throw new Error("Failed to extract data from image after multiple attempts.");
};

export async function extractFromImages(formData: FormData) {
  const netFile = formData.get("net_weight") as File;
  const grossFile = formData.get("gross_weight") as File;
  const bufferFile = formData.get("buffer") as File;

  if (!netFile || !grossFile || !bufferFile) {
    throw new Error("All three files are required.");
  }

  const netPart = await getFilePart(netFile);
  const grossPart = await getFilePart(grossFile);
  const bufferPart = await getFilePart(bufferFile);

  const netData = await extractData(netPart);
  const grossData = await extractData(grossPart);
  const bufferData = await extractData(bufferPart);

  // Compare vehicle numbers from each image
  const netVehicleNumber = netData.vehicle_number;
  const grossVehicleNumber = grossData.vehicle_number;
  const bufferVehicleNumber = bufferData.vehicle_number;

  if (
    netVehicleNumber === grossVehicleNumber &&
    grossVehicleNumber === bufferVehicleNumber
  ) {
    // Vehicle numbers match, insert data into Prisma
    // const createdData = addOCRData()
    // // Return the data inserted
    // return createdData;
  } else {
    // Vehicle numbers do not match
    throw new Error("Vehicle numbers do not match between the three images.");
  }
}

export async function addOCRData(data: ocr) {
  try {
    const headerList = await headers();

    await prisma.audit.create({
      data: {
        ip: headerList.get("x-forwarded-for") ?? "0.0.0.0",
        message: "create bill",
      },
    });
    return await prisma.ocr.create({
      data: { ...data, id: undefined },
    });
  } catch (error) {
    return Error("error");
  }
}

const E_WAYBILL_PROMPT = `
**E-Way Bill Number and Date Extraction Prompt (For PDF)**

You are provided with a PDF document that contains logistics or shipment information.

**Your task is:**

* Extract the **E-Way Bill Number** and its corresponding **Generated Date** from the document.

* The E-Way Bill Number is a **12-digit numeric value**.

* The **Generated Date** is usually in the format **DD/MM/YYYY** or **DD-MM-YYYY** and appears near the E-Way Bill Number.

* E-Way Bill Number is often labeled as:

  * \`eWay Bill No:\`
  * \`E-Way Bill No:\`
  * or appears near the phrase “Generated Date” or “Generated By”.

* Return the result as a list of objects in the following format:

\`\`\`

  {
    "eway_bill_no": "691863991440",
    "generated_date": "05/06/2024"
  }

\`\`\`

* If multiple E-Way Bill Numbers and dates are present, return all of them in the same format.

Do not include any explanation, headers, or extra formatting—only return the JSON or not in array form only in json object..

`;

export const extractEWayBill = async (
  filePart: any,
  maxRetries = 3
): Promise<{
  eway_bill_no: string;
  generated_date: string;
}> => {
  let attempt = 0;
  while (attempt < maxRetries) {
    try {
      const result = await model.generateContent({
        contents: [
          {
            role: "user",
            parts: [{ text: E_WAYBILL_PROMPT }, filePart],
          },
        ],
      });

      const jsonText = await result.response.text();
      const jsonString = jsonText.replace(/^```json\s*|\s*```$/g, "");
      console.log(`Extracted JSON (attempt ${attempt + 1}):`, jsonString);

      return JSON.parse(jsonString);
    } catch (error) {
      console.error(`Attempt ${attempt + 1} failed:`, error);
      attempt++;

      // Optional: wait before retrying
      await new Promise((res) => setTimeout(res, 500 * attempt));
    }
  }
  throw new Error("Failed to extract data from image after multiple attempts.");
};

const E_WAYBILL_PROMPT_in = `

**E-Way Bill, Challan/Invoice Number, and Vehicle Number Extraction Prompt (For PDF)**

You are provided with a PDF document that contains logistics or shipment information.

**Your task is:**

* Extract the **E-Way Bill Number** from the document.

  * A **12-digit numeric** value.
  * Often labeled as:

    * \`eWay Bill No:\`
    * \`E-Way Bill No:\`
    * or appears near "Generated Date" or "Generated By".

* Extract the **Challan No** or **Invoice No**.

  * May be alphanumeric.
  * Labeled as:

    * \`Challan No:\`
    * \`Challan \`
    * \`Challan Number:\`
    * \`Invoice No:\`
    * \`Invoice Number:\`
    * \`Document Number:\`
    * \`Document No.\`

* Extract the **Generated Date**.

  * Format: **DD/MM/YYYY** or **DD-MM-YYYY**.
  * Usually near the E-Way Bill Number.

* Extract the **Vehicle Number**.

  * Follows Indian vehicle registration format.

    * Examples: \`MH-12AB-1234\`, \`RJ20GC4556\`, \`UP45AT9123\`
  * May appear:

    * Near labels like \`Vehicle No:\`, \`Vehicle Number:\`, \`Trans Vehicle:\`
    * Or under the label **\`Vehicle / Trans Doc No & Dt.\`**
    * May include or exclude hyphens.

**Return Format:**

Return only the first occurrence of each value in this exact JSON format:

\`\`\`json
{
  "EWayBillNumber": "691863991440",
  "ChallanOrInvoiceNumber": "INV/23-24/0198",
  "generated_date": "05/06/2024",
  "vehicle_number": "UP45AT9123"
}
\`\`\`

`;

export const extractEWayBill_withIn = async (
  filePart: any,
  maxRetries = 3
): Promise<{
  EWayBillNumber: string;
  ChallanOrInvoiceNumber: string;
  generated_date: string;
  vehicle_number: string;
}> => {
  let attempt = 0;
  while (attempt < maxRetries) {
    try {
      const result = await model.generateContent({
        contents: [
          {
            role: "user",
            parts: [{ text: E_WAYBILL_PROMPT_in }, filePart],
          },
        ],
      });

      const jsonText = await result.response.text();
      const jsonString = jsonText.replace(/^```json\s*|\s*```$/g, "");
      console.log(`Extracted JSON (attempt ${attempt + 1}):`, jsonString);

      return JSON.parse(jsonString);
    } catch (error) {
      console.error(`Attempt ${attempt + 1} failed:`, error);
      attempt++;

      // Optional: wait before retrying
      await new Promise((res) => setTimeout(res, 500 * attempt));
    }
  }
  throw new Error("Failed to extract data from image after multiple attempts.");
};

const Compare_PROMPT = `
Extract the following information from each uploaded PDF file **strictly following the format and rules below**.

### **Required Fields (return in JSON):**
\`\`\`json
{
  "vehicle_number": "UP45AT9123",
  "date": "14-05-2025",
  "net_weight": "1240.5 kg"
}
\`\`\`

---

### **Field Rules:**

* **\`vehicle_number\`**: Extract the full vehicle number exactly as it appears (e.g., \`"UP45AT9123"\`). If missing, return \`null\`.

* **\`date\`**: Extract the date in **DD-MM-YYYY** format (e.g., \`"14-05-2025"\`). If in another format, convert it. If unrecognizable, return \`null\`.

* **\`net_weight\`**:

  * Extract the weight value as a **number followed by its unit** (e.g., \`"1240.5 kg"\`).
  * **Remove any trailing \`.00\`** from the number (e.g., convert \`"39330.00"\` → \`"39330"\`).
  * Preserve the original **unit** use only "kg".
  * If the weight is not found, return \`null\`.
  * it alice name is Material Weight


### **Output Requirements:**

* Return a **JSON object**.
* The keys \`vehicle_number\`, \`date\`, and \`net_weight\` **must always be present**.
* Use \`null\` if any value is missing.
* Do not include any additional fields.

### **Example Outputs:**

\`\`\`json
{
  "vehicle_number": "UP45AT9123",
  "date": "14-05-2025",
  "net_weight": "39330 KGS"
}
\`\`\`

\`\`\`json
{
  "vehicle_number": null,
  "date": "12-04-2025",
  "net_weight": "5.2 MT"
}
\`\`\`
**Important:** The number must not contain any commas, spaces, or extra characters (e.g., use \`"1240.5"\` not \`"1,240.5"\` or \`"1240.5 kg."\`).
`;

type ExtractDataFORComparJsonType = {
  vehicle_number: string;
  date: string;
  net_weight: string;
};
export const ExtractDataFORCompar = async (
  filePart: any,
  maxRetries = 3
): Promise<ExtractDataFORComparJsonType> => {
  let attempt = 0;
  while (attempt < maxRetries) {
    try {
      const result = await model.generateContent({
        contents: [
          {
            role: "user",
            parts: [{ text: Compare_PROMPT }, filePart],
          },
        ],
      });

      const jsonText = await result.response.text();
      const jsonString = jsonText.replace(/^```json\s*|\s*```$/g, "");
      console.log(`Extracted JSON (attempt ${attempt + 1}):`, jsonString);

      return JSON.parse(jsonString);
    } catch (error) {
      console.error(`Attempt ${attempt + 1} failed:`, error);
      attempt++;

      // Optional: wait before retrying
      await new Promise((res) => setTimeout(res, 500 * attempt));
    }
  }
  throw new Error("Failed to extract data from image after multiple attempts.");
};

export async function UpdateOCRData(id: number, data: Partial<ocr>) {
  try {
    return await prisma.ocr.update({
      where: { id },
      data,
    });
  } catch (error) {
    return Error("error");
  }
}

export async function getAllOcr() {
  return await prisma.ocr.findMany({
    take: 10,
    orderBy: {
      created_at: "desc",
    },
  });
}

export async function getOcr(id: number) {
  return await prisma.ocr.findUnique({
    where: {
      id,
    },
    include: {
      company: true,
    },
  });
}

export async function ocrCount(companyID: number) {
  return await prisma.ocr.count({
    where: {
      company: {
        id: companyID,
      },
    },
  });
}

const EXtractPrompt = `
I have multiple PDF files. Each one contains a Delivery Challan.

Please extract only the Challan Number from each PDF. The challan number may appear as:

"Challan No"

"Challan Number"

"Delivery Challan No"

"DC No"

or similar variations.

Return the result in this JSON format:


[
  {
    "file_name": "example1.pdf",
    "challan_number": "DC-00123"
  },
  {
    "file_name": "example2.pdf",
    "challan_number": "CH-45678"
  }
]
If a challan number is not found in a file, set "challan_number" to null.

`;

export async function getChallanNumber(filePart: any[], maxRetries = 3) {
  let attempt = 0;
  while (attempt < maxRetries) {
    try {
      const result = await model.generateContent({
        contents: [
          {
            role: "user",
            parts: [{ text: EXtractPrompt }, ...filePart],
          },
        ],
      });

      const jsonText = await result.response.text();
      const jsonString = jsonText.replace(/^```json\s*|\s*```$/g, "");
      console.log(`Extracted JSON (attempt ${attempt + 1}):`, jsonString);

      return JSON.parse(jsonString);
    } catch (error) {
      console.error(`Attempt ${attempt + 1} failed:`, error);
      attempt++;

      // Optional: wait before retrying
      await new Promise((res) => setTimeout(res, 500 * attempt));
    }
  }
  throw new Error("Failed to extract data from image after multiple attempts.");
}

const sPrompt = `
You are given **two separate PDFs**:

* One containing **Challan/Invoice details**
* One containing **E-Way Bill details**

Your task is to extract the following:

* From the **Challan PDF**:

  * \`challan_number\`
  * \`challan_date\`
* From the **E-Way Bill PDF**:
>
  * \`eway_bill_number\`
  * \`eway_bill_date\`
>
**Instructions:**
>
* Return a **single merged JSON object** with these fields.
* If a field is not found, return \`"Not Found"\`.
* Format all dates as \`DD-MM-YYYY\`.
>
**Output Example:**
>
\`\`\`json
{
  "challan_number": "INV-00123",
  "challan_date": "03-05-2025",
  "eway_bill_number": "EW123456789",
  "eway_bill_date": "04-05-2025"
}
  \`\`\`
`;
type MsiData = {
  challan_number: string;
  challan_date: string;
  eway_bill_number: string;
  eway_bill_date: string;
};
export async function extractData_msi(
  filePart: any[],
  maxRetries = 3
): Promise<MsiData> {
  let attempt = 0;
  while (attempt < maxRetries) {
    try {
      const result = await model.generateContent({
        contents: [
          {
            role: "user",
            parts: [{ text: sPrompt }, ...filePart],
          },
        ],
      });

      const jsonText = await result.response.text();
      const jsonString = jsonText.replace(/^```json\s*|\s*```$/g, "");
      console.log(`Extracted JSON (attempt ${attempt + 1}):`, jsonString);

      return JSON.parse(jsonString);
    } catch (error) {
      console.error(`Attempt ${attempt + 1} failed:`, error);
      attempt++;

      // Optional: wait before retrying
      await new Promise((res) => setTimeout(res, 500 * attempt));
    }
  }
  throw new Error("Failed to extract data from image after multiple attempts.");
}

const slipPrompt = `
Extract the following data from this image of a logistics or delivery document. If a field is not present, return "Not found". Use OCR and return results in structured JSON format.

Fields to extract:

* Truck Number (\`truck_no\`)
* CHL Delivery Order Number (\`chl_del_ord_no\`)
* Supplier Name (\`supplier_name\`)
* Date In (\`date_in\`)
* Date Out (\`date_out\`)
* Time In (\`time_in\`)
* Time Out (\`time_out\`)
* Gross Weight (\`gross_weight\`)
* Tare Weight (\`tare_weight\`)
* Net Weight (\`net_weight\`)

**Return format (JSON):**

\`\`\`json
{
  "truck_no": "",
  "chl_del_ord_no": "",
  "supplier_name": "",
  "date_in": "",
  "date_out": "",
  "time_in": "",
  "time_out": "",
  "gross_weight": "",
  "tare_weight": "",
  "net_weight": ""
}
\`\`\`


`;
export type slipType = {
  truck_no: string;
  chl_del_ord_no: string;
  supplier_name: string;
  date_in: string;
  date_out: string;
  time_in: string;
  time_out: string;
  gross_weight: string;
  tare_weight: string;
  net_weight: string;
};
export async function extractData_slipData(
  filePart: any,
  maxRetries = 3
): Promise<slipType> {
  let attempt = 0;
  while (attempt < maxRetries) {
    try {
      const result = await model.generateContent({
        contents: [
          {
            role: "user",
            parts: [{ text: slipPrompt }, filePart],
          },
        ],
      });

      const jsonText = await result.response.text();
      const jsonString = jsonText.replace(/^```json\s*|\s*```$/g, "");
      console.log(`Extracted JSON (attempt ${attempt + 1}):`, jsonString);

      return JSON.parse(jsonString);
    } catch (error) {
      console.error(`Attempt ${attempt + 1} failed:`, error);
      attempt++;

      // Optional: wait before retrying
      await new Promise((res) => setTimeout(res, 500 * attempt));
    }
  }
  throw new Error("Failed to extract data from image after multiple attempts.");
}

export async function deleteOcr(id: number) {
  if (!id) return;

  const existing = await prisma.ocr.findUnique({ where: { id } });

  if (!existing) {
    throw new Error(`Record with id ${id} does not exist.`);
  }

  await prisma.ocr.delete({ where: { id } });
}

const PROMPT_All_WIGHT = `



**Image Data Extraction Prompt**

You are given three images.

Extract the following properties:

* **gross_weight** (Int)
* **tare_weight** (Int)
* **net_weight** (Int)
* **vehicle_number** (String)
* **address** (String)
* **map_url** (Google Maps URL)
* **latitude** (float)
* **longitude** (float)
* **date** (DateTime)

If a field is not found in the image, set its value to \`null\`.

**Return only JSON in the following format:**

\`\`\`json
{
  "gross_weight": 1500,
  "tare_weight": 500,
  "net_weight": 1000,
  "vehicle_number": "RJ-20GC-4556",
  "address": "1234 Main St, Cityville, Country",
  "map_url": "https://maps.google.com/?q=12.345678,-98.765432",
  "latitude": 12.34567,
  "longitude": -98.76543,
  "date": "2025-04-25T15:30:00Z"
}
\`\`\`

Example when some fields are missing:

\`\`\`json
{
  "gross_weight": null,
  "tare_weight": null,
  "net_weight": null,
  "vehicle_number": null,
  "address": null,
  "map_url": null,
  "latitude": null,
  "longitude": null,
  "date": null
}
\`\`\`

Return only JSON.
`;

export async function extractData_AllWight(
  filePart: any,
  maxRetries = 3
): Promise<{
  gross_weight: null | number;
  tare_weight: null | number;
  net_weight: null | number;
  vehicle_number: null | string;
  address: null | string;
  map_url: null | string;
  latitude: null | number;
  longitude: null | number;
  date: null | string;
}> {
  let attempt = 0;
  while (attempt < maxRetries) {
    try {
      const result = await model.generateContent({
        contents: [
          {
            role: "user",
            parts: [{ text: PROMPT_All_WIGHT }, filePart],
          },
        ],
      });

      const jsonText = await result.response.text();
      const jsonString = jsonText.replace(/^```json\s*|\s*```$/g, "");
      console.log(`Extracted JSON (attempt ${attempt + 1}):`, jsonString);

      return JSON.parse(jsonString);
    } catch (error) {
      console.error(`Attempt ${attempt + 1} failed:`, error);
      attempt++;

      // Optional: wait before retrying
      await new Promise((res) => setTimeout(res, 500 * attempt));
    }
  }
  throw new Error("Failed to extract data from image after multiple attempts.");
}

export async function addMedia(title: string, content: File, ocrId: number) {
  const headerList = await headers();

  await prisma.audit.create({
    data: {
      ip: headerList.get("x-forwarded-for") ?? "0.0.0.0",
      message: `${title} - File upload`,
    },
  });
  const b = Buffer.from(await content.arrayBuffer()).toString("base64");
  return prisma.media.create({
    data: {
      title,
      content: b,
      type: content.type,
      ocr: {
        connect: {
          id: ocrId,
        },
      },
    },
  });
}

export async function getOcrByCompany(companyId?: number) {
  const where = companyId ? { companyDetailId: companyId } : {};

  return await prisma.ocr.findMany({
    where,
    include: {
      company: true,
      vendor: true,
      medias: true,
    },
    orderBy: { created_at: "desc" },
  });
}
export async function getCompanies() {
  return await prisma.companyDetail.findMany({
    select: {
      id: true,
      name: true,
    },
    orderBy: { name: "asc" },
  });
}
